version: "3.8"

services:
  nodejs-ws1:
    build: ./nodejs-ws1
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
      - minio

  nodejs-ws2:
    build: ./nodejs-ws2
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
      - minio

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit deprecated_features permit_management_metrics_collection true
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  openalpr-worker1:
    build: ./openalpr-worker1
    depends_on:
      - rabbitmq

  openalpr-worker2:
    build: ./openalpr-worker2
    depends_on:
      - rabbitmq